# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\home\sptraj\trajproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\home\sptraj\trajproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components\fast: list_install_components

.PHONY : list_install_components\fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# Special rule for the target install/local
install\local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local

# Special rule for the target install/local
install\local\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\home\sptraj\trajproject\CMakeFiles D:\home\sptraj\trajproject\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\home\sptraj\trajproject\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) main
.PHONY : main

# fast build rule for target.
main\fast:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\build
.PHONY : main\fast

plantform\main.obj: plantform\main.cpp.obj

.PHONY : plantform\main.obj

# target to build an object file
plantform\main.cpp.obj:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\main.cpp.obj
.PHONY : plantform\main.cpp.obj

plantform\main.i: plantform\main.cpp.i

.PHONY : plantform\main.i

# target to preprocess a source file
plantform\main.cpp.i:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\main.cpp.i
.PHONY : plantform\main.cpp.i

plantform\main.s: plantform\main.cpp.s

.PHONY : plantform\main.s

# target to generate assembly for a file
plantform\main.cpp.s:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\main.cpp.s
.PHONY : plantform\main.cpp.s

plantform\modelbase.obj: plantform\modelbase.cpp.obj

.PHONY : plantform\modelbase.obj

# target to build an object file
plantform\modelbase.cpp.obj:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\modelbase.cpp.obj
.PHONY : plantform\modelbase.cpp.obj

plantform\modelbase.i: plantform\modelbase.cpp.i

.PHONY : plantform\modelbase.i

# target to preprocess a source file
plantform\modelbase.cpp.i:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\modelbase.cpp.i
.PHONY : plantform\modelbase.cpp.i

plantform\modelbase.s: plantform\modelbase.cpp.s

.PHONY : plantform\modelbase.s

# target to generate assembly for a file
plantform\modelbase.cpp.s:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\modelbase.cpp.s
.PHONY : plantform\modelbase.cpp.s

plantform\odeengin.obj: plantform\odeengin.cpp.obj

.PHONY : plantform\odeengin.obj

# target to build an object file
plantform\odeengin.cpp.obj:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\odeengin.cpp.obj
.PHONY : plantform\odeengin.cpp.obj

plantform\odeengin.i: plantform\odeengin.cpp.i

.PHONY : plantform\odeengin.i

# target to preprocess a source file
plantform\odeengin.cpp.i:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\odeengin.cpp.i
.PHONY : plantform\odeengin.cpp.i

plantform\odeengin.s: plantform\odeengin.cpp.s

.PHONY : plantform\odeengin.s

# target to generate assembly for a file
plantform\odeengin.cpp.s:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\odeengin.cpp.s
.PHONY : plantform\odeengin.cpp.s

plantform\recorder.obj: plantform\recorder.cpp.obj

.PHONY : plantform\recorder.obj

# target to build an object file
plantform\recorder.cpp.obj:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\recorder.cpp.obj
.PHONY : plantform\recorder.cpp.obj

plantform\recorder.i: plantform\recorder.cpp.i

.PHONY : plantform\recorder.i

# target to preprocess a source file
plantform\recorder.cpp.i:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\recorder.cpp.i
.PHONY : plantform\recorder.cpp.i

plantform\recorder.s: plantform\recorder.cpp.s

.PHONY : plantform\recorder.s

# target to generate assembly for a file
plantform\recorder.cpp.s:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\recorder.cpp.s
.PHONY : plantform\recorder.cpp.s

plantform\rk1.obj: plantform\rk1.c.obj

.PHONY : plantform\rk1.obj

# target to build an object file
plantform\rk1.c.obj:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\rk1.c.obj
.PHONY : plantform\rk1.c.obj

plantform\rk1.i: plantform\rk1.c.i

.PHONY : plantform\rk1.i

# target to preprocess a source file
plantform\rk1.c.i:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\rk1.c.i
.PHONY : plantform\rk1.c.i

plantform\rk1.s: plantform\rk1.c.s

.PHONY : plantform\rk1.s

# target to generate assembly for a file
plantform\rk1.c.s:
	$(MAKE) -f CMakeFiles\main.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\main.dir\plantform\rk1.c.s
.PHONY : plantform\rk1.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... list_install_components
	@echo ... main
	@echo ... edit_cache
	@echo ... install
	@echo ... rebuild_cache
	@echo ... install/local
	@echo ... plantform/main.obj
	@echo ... plantform/main.i
	@echo ... plantform/main.s
	@echo ... plantform/modelbase.obj
	@echo ... plantform/modelbase.i
	@echo ... plantform/modelbase.s
	@echo ... plantform/odeengin.obj
	@echo ... plantform/odeengin.i
	@echo ... plantform/odeengin.s
	@echo ... plantform/recorder.obj
	@echo ... plantform/recorder.i
	@echo ... plantform/recorder.s
	@echo ... plantform/rk1.obj
	@echo ... plantform/rk1.i
	@echo ... plantform/rk1.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

